### ISSUE TITLE
could not compile

### ISSUE THREAD

**Issue by bing050802** [jazzfool/otway#1]
137 |           gfx::skia::SkiaGraphicsDisplay::new_gl_framebuffer(&gfx::skia::SkiaOpenGlFramebuffer {
    |  _________^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^_-
    | |         |
    | |         expected 2 arguments

**Comment by jazzfool** [comment]
Fixed. Be aware I no longer work on this project so I don't recommend you use it.
